import { initializePushNotifications } from './pushNotifications';
import { setupAutoSync } from './offlineSync';

export async function registerServiceWorker(): Promise<void> {
  if (!('serviceWorker' in navigator)) {
    console.warn('Service Workers not supported');
    return;
  }

  try {
    // Service worker will be automatically generated by vite-plugin-pwa
    const registration = await navigator.serviceWorker.register('/sw.js', {
      scope: '/',
    });

    console.log('Service Worker registered:', registration);

    // Initialize push notifications
    await initializePushNotifications(registration);

    // Setup automatic offline sync
    setupAutoSync();

    // Check for updates
    registration.addEventListener('updatefound', () => {
      const newWorker = registration.installing;
      
      if (newWorker) {
        newWorker.addEventListener('statechange', () => {
          if (newWorker.state === 'installed' && navigator.serviceWorker.controller) {
            // New service worker available
            showUpdateNotification();
          }
        });
      }
    });

  } catch (error) {
    console.error('Service Worker registration failed:', error);
  }
}

function showUpdateNotification(): void {
  if ('Notification' in window && Notification.permission === 'granted') {
    const notification = new Notification('Update Available', {
      body: 'A new version of FlavorCore is available. Tap to update.',
      icon: '/flavorcore-logo.png',
      tag: 'app-update',
      requireInteraction: true,
    });

    notification.onclick = () => {
      window.location.reload();
    };
  } else {
    // Fallback: Show in-app banner
    const banner = document.createElement('div');
    banner.style.cssText = `
      position: fixed;
      top: 0;
      left: 0;
      right: 0;
      background: #7C3AED;
      color: white;
      padding: 16px;
      text-align: center;
      z-index: 9999;
      cursor: pointer;
    `;
    banner.textContent = 'Update available! Tap to refresh.';
    banner.onclick = () => window.location.reload();
    document.body.appendChild(banner);
  }
}